<?php

namespace Database\Seeders;

use App\Models\Keyword;
use App\Models\Taxonomy;
use App\Models\Location;
use Illuminate\Database\Seeder;

class KeywordSeeder extends Seeder
{
    public function run(): void
    {
        $taxonomies = Taxonomy::whereNotNull('parent_id')->get();
        $locations = Location::whereNotNull('parent_id')->get();

        if ($taxonomies->isEmpty() || $locations->isEmpty()) {
            $this->command->warn('Taxonomies or locations not found. Run TaxonomySeeder and LocationSeeder first.');
            return;
        }

        $keywords = [
            ['keyword' => 'İstanbul kombi servisi', 'volume' => 5400, 'difficulty' => 65],
            ['keyword' => 'Ankara kombi servisi', 'volume' => 3200, 'difficulty' => 58],
            ['keyword' => 'İzmir kombi tamiri', 'volume' => 2100, 'difficulty' => 52],
            ['keyword' => 'Kombi bakımı İstanbul', 'volume' => 1900, 'difficulty' => 48],
            ['keyword' => 'Kombi arızası', 'volume' => 4800, 'difficulty' => 70],
            ['keyword' => 'Kombi montaj', 'volume' => 2600, 'difficulty' => 55],
            ['keyword' => 'Kombi gaz ayarı', 'volume' => 1400, 'difficulty' => 42],
            ['keyword' => 'Kombi ekran hatası', 'volume' => 900, 'difficulty' => 35],
            ['keyword' => 'Kombi petek temizliği', 'volume' => 1800, 'difficulty' => 45],
            ['keyword' => 'Kombi su akıtıyor', 'volume' => 1100, 'difficulty' => 38],
            ['keyword' => 'Klima tamiri', 'volume' => 6700, 'difficulty' => 72],
            ['keyword' => 'Klima montajı', 'volume' => 4100, 'difficulty' => 60],
            ['keyword' => 'Klima bakım', 'volume' => 2300, 'difficulty' => 50],
            ['keyword' => 'Klima soğutmuyor', 'volume' => 1900, 'difficulty' => 55],
            ['keyword' => 'Klima gaz dolumu', 'volume' => 1500, 'difficulty' => 45],
            ['keyword' => 'Kalorifer kazanı', 'volume' => 1700, 'difficulty' => 52],
            ['keyword' => 'Kalorifer petek', 'volume' => 1200, 'difficulty' => 40],
            ['keyword' => 'Radyatör montaj', 'volume' => 980, 'difficulty' => 35],
            ['keyword' => 'Doğalgaz tesisatı', 'volume' => 2200, 'difficulty' => 58],
            ['keyword' => 'Tesisatçı', 'volume' => 8100, 'difficulty' => 75],
        ];

        $trendingKeywords = ['kombi arızası', 'klima tamiri', 'kombi bakımı'];
        $autoGeneratedKeywords = ['kombi servisi', 'klima servisi'];

        foreach ($keywords as $index => $data) {
            $taxonomy = $taxonomies->random();
            $location = $locations->random();

            $keyword = Keyword::create([
                'keyword' => $data['keyword'],
                'slug' => \App\Helpers\SlugGenerator::generateKeywordSlug($data['keyword']),
                'language' => 'tr',
                'category_id' => $taxonomy->id,
                'location_id' => $location->id,
                'search_volume' => $data['volume'],
                'difficulty' => $data['difficulty'],
                'is_trending' => in_array($data['keyword'], $trendingKeywords),
                'is_auto_generated' => in_array($data['keyword'], $autoGeneratedKeywords),
                'clicks' => rand(0, $data['volume'] / 10),
                'impressions' => rand($data['volume'] / 2, $data['volume']),
                'position' => rand(10, 50) + rand(0, 99) / 100,
            ]);
        }

        $this->command->info('KeywordSeeder: ' . count($keywords) . ' keywords created.');
    }
}