"""
config.py — Configuration for Keyword Orchestra
=================================================
"""

import os

API_BASE_URL = os.getenv("API_BASE_URL", "http://localhost:8000")
API_TOKEN = os.getenv("API_TOKEN", "")

API_ENDPOINTS = {
    "keywords": "/api/v1/orchestra/keywords",
    "sync_countries": "/api/v1/orchestra/sync-countries",
    "status": "/api/v1/orchestra/status",
}

BATCH_SIZE = 100
REQUEST_TIMEOUT = 30
MAX_RETRIES = 3

EUROPE_COUNTRIES = [
    {"code": "TR", "name": "Turkey", "language": "tr"},
    {"code": "GB", "name": "United Kingdom", "language": "en"},
    {"code": "DE", "name": "Germany", "language": "de"},
    {"code": "FR", "name": "France", "language": "fr"},
    {"code": "ES", "name": "Spain", "language": "es"},
    {"code": "IT", "name": "Italy", "language": "it"},
    {"code": "NL", "name": "Netherlands", "language": "nl"},
    {"code": "BE", "name": "Belgium", "language": "nl"},
    {"code": "AT", "name": "Austria", "language": "de"},
    {"code": "CH", "name": "Switzerland", "language": "de"},
    {"code": "PL", "name": "Poland", "language": "pl"},
    {"code": "SE", "name": "Sweden", "language": "sv"},
    {"code": "NO", "name": "Norway", "language": "no"},
    {"code": "DK", "name": "Denmark", "language": "da"},
    {"code": "FI", "name": "Finland", "language": "fi"},
    {"code": "PT", "name": "Portugal", "language": "pt"},
    {"code": "GR", "name": "Greece", "language": "el"},
    {"code": "IE", "name": "Ireland", "language": "en"},
    {"code": "CZ", "name": "Czech Republic", "language": "cs"},
    {"code": "HU", "name": "Hungary", "language": "hu"},
    {"code": "RO", "name": "Romania", "language": "ro"},
    {"code": "BG", "name": "Bulgaria", "language": "bg"},
    {"code": "SK", "name": "Slovakia", "language": "sk"},
    {"code": "HR", "name": "Croatia", "language": "hr"},
    {"code": "SI", "name": "Slovenia", "language": "sl"},
    {"code": "RS", "name": "Serbia", "language": "sr"},
    {"code": "UA", "name": "Ukraine", "language": "uk"},
    {"code": "RU", "name": "Russia", "language": "ru"},
]

GLOBAL_COUNTRIES = [
    {"code": "US", "name": "United States", "language": "en"},
    {"code": "CA", "name": "Canada", "language": "en"},
    {"code": "BR", "name": "Brazil", "language": "pt"},
    {"code": "AR", "name": "Argentina", "language": "es"},
    {"code": "MX", "name": "Mexico", "language": "es"},
    {"code": "CO", "name": "Colombia", "language": "es"},
    {"code": "CL", "name": "Chile", "language": "es"},
    {"code": "PE", "name": "Peru", "language": "es"},
    {"code": "AU", "name": "Australia", "language": "en"},
    {"code": "NZ", "name": "New Zealand", "language": "en"},
    {"code": "JP", "name": "Japan", "language": "ja"},
    {"code": "KR", "name": "South Korea", "language": "ko"},
    {"code": "IN", "name": "India", "language": "hi"},
    {"code": "ID", "name": "Indonesia", "language": "id"},
    {"code": "TH", "name": "Thailand", "language": "th"},
    {"code": "VN", "name": "Vietnam", "language": "vi"},
    {"code": "MY", "name": "Malaysia", "language": "ms"},
    {"code": "SG", "name": "Singapore", "language": "en"},
    {"code": "PH", "name": "Philippines", "language": "en"},
    {"code": "PK", "name": "Pakistan", "language": "ur"},
    {"code": "EG", "name": "Egypt", "language": "ar"},
    {"code": "SA", "name": "Saudi Arabia", "language": "ar"},
    {"code": "AE", "name": "United Arab Emirates", "language": "ar"},
    {"code": "IL", "name": "Israel", "language": "he"},
    {"code": "ZA", "name": "South Africa", "language": "en"},
    {"code": "NG", "name": "Nigeria", "language": "en"},
    {"code": "KE", "name": "Kenya", "language": "en"},
]

ALL_COUNTRIES = EUROPE_COUNTRIES + GLOBAL_COUNTRIES

COUNTRY_LANGUAGE_MAP = {c["code"]: c["language"] for c in ALL_COUNTRIES}

SAMPLE_KEYWORDS = {
    "tr": ["kombi", "klima", "doğalgaz", "petek", "thermostat", "kazan", "ısıtma", "soğutma",
           "tesisat", "elektrik", "nakliye", "boya", "badana", "çilingir", "temizlik"],
    "en": ["boiler", "hvac", "air conditioning", "heating", "thermostat", "furnace", "heat pump",
           "plumber", "electrician", "roofing", "landscaping", "cleaning", "painting", "moving",
           "pest control", "carpet cleaning", "garage door", "flooring", "remodeling", "fencing"],
    "de": ["Heizung", "Klimaanlage", "Kessel", "Thermostat", "Heizkörper", "Sanitär", "Elektriker",
           "Dachdecker", "Gartenbau", "Reinigung", "Maler", "Umzug", "Schädlingsbekämpfung"],
    "fr": ["chauffage", "climatisation", "chaudière", "thermostat", "plombier", "électricien",
           "couverture", "jardinage", "nettoyage", "peinture", "déménagement", "désinsectisation"],
    "es": ["calefacción", "aire acondicionado", "caldera", "termostato", "fontanero", "electricista",
           "techos", "jardinería", "limpieza", "pintura", "mudanzas", "control de plagas"],
    "it": ["riscaldamento", "climatizzazione", "caldaia", "termostato", "idraulico", "elettricista",
           "tetti", "giardinaggio", "pulizia", "pittura", "traslochi", "disinfestazione"],
    "nl": ["verwarming", "airconditioning", "ketel", "thermostaat", "loodgieter", "elektricien",
           "dakbedekking", "tuinieren", "schoonmaak", "schilderen", "verhuizing", "ongediertebestrijding"],
    "pl": ["ogrzewanie", "klimatyzacja", "kocioł", "termostat", "hydraulik", "elektryk",
           "dekarski", "ogrodnictwo", "sprzątanie", "malowanie", "przeprowadzki", "deratyzacja"],
    "sv": ["värme", "luftkonditionering", "panna", "termostat", "rörmokare", "elektriker",
           "takläggning", "trädgårdsskötsel", "städning", "målning", "flytt", "skadedjursbekämpning"],
    "no": ["oppvarming", "aircondition", "kjel", "termostat", "rørlegger", "elektriker",
           "taktekking", "hagearbeid", "rengjøring", "maling", "flytting", "skadedyrkontroll"],
    "da": ["varme", "aircondition", "kedel", "termostat", "blikkenslager", "elektriker",
           "tagdækning", "havearbejde", "rengøring", "maling", "flytning", "skadedyrsbekæmpelse"],
    "fi": ["lämmitys", "ilmastointi", "kattila", "termostaatti", "putkimies", "sähköasentaja",
           "kattohuolto", "puutarhanhoito", "siivous", "maalaus", "muutto", "tuholaistorjunta"],
    "pt": ["aquecimento", "ar condicionado", "caldeira", "termostato", "canalizador", "eletricista",
           "telhados", "jardinagem", "limpeza", "pintura", "mudanças", "controle de pragas"],
    "el": ["θέρμανση", "κλιματισμός", "λέβητας", "θερμοστάτης", "υδραυλικός", "ηλεκτρολόγος",
           "στέγες", "κηπουρική", "καθαρισμός", "βάψιμο", "μετακόμιση", "απεντόμωση"],
    "cs": ["topení", "klimatizace", "kotel", "termostat", "instalatér", "elektrikář",
           "střechy", "zahradnictví", "úklid", "malování", "stěhování", "deratizace"],
    "hu": ["fűtés", "légkondicionáló", "kazán", "termosztát", "vízvezeték-szerelő", "villanyszerelő",
           "tetőfedés", "kertészet", "takarítás", "festés", "költöztetés", "kártevőirtás"],
    "ro": ["încălzire", "aer condiționat", "centrală", "termostat", "instalator", "electrician",
           "acoperișuri", "grădinărit", "curățenie", "zugrăvit", "mutări", "dezinsecție"],
    "bg": ["отопление", "климатизация", "котел", "термостат", "водопроводчик", "електротехник",
           "покриви", "градинарство", "почистване", "боядисване", "преместване", "дезинсекция"],
    "sk": ["kúrenie", "klimatizácia", "kotol", "termostat", "inštalatér", "elektrikár",
           "strechy", "záhradníctvo", "čistenie", "maľovanie", "sťahovanie", "deratizácia"],
    "hr": ["grijanje", "klimatizacija", "kotao", "termostat", "vodoinstalater", "električar",
           "krovovi", "vrtlarstvo", "čišćenje", "bojanje", "selidbe", "deratizacija"],
    "sl": ["ogrevanje", "klimatizacija", "kotel", "termostat", "vodovodar", "električar",
           "strehe", "vrtnarstvo", "čiščenje", "barvanje", "selitve", "deratizacija"],
    "sr": ["grejanje", "klimatizacija", "kotao", "termostat", "vodoinstalater", "električar",
           "krovovi", "baštovanstvo", "čišćenje", "farbanje", "selidbe", "deratizacija"],
    "uk": ["опалення", "кондиціонування", "котел", "термостат", "сантехнік", "електрик",
           "покрівля", "садівництво", "прибирання", "фарбування", "переїзд", "дезінсекція"],
    "ru": ["отопление", "кондиционирование", "котел", "термостат", "сантехник", "электрик",
           "кровля", "садоводство", "уборка", "покраска", "переезд", "дезинсекция"],
    "ja": ["暖房", "エアコン", "ボイラー", "サーモスタット", "配管工", "電気工事士",
           "屋根工事", "造園", "掃除", "塗装", "引越し", "害虫駆除"],
    "ko": ["난방", "에어컨", "보일러", "온도조절기", "배관공", "전기기사",
           "지붕공사", "조경", "청소", "도장", "이사", "해충방제"],
    "hi": ["हीटिंग", "एसी", "बॉयलर", "थर्मोस्टेट", "प्लंबर", "इलेक्ट्रीशियन",
           "छत का काम", "बागवानी", "सफाई", "पेंटिंग", "शिफ्टिंग", "कीट नियंत्रण"],
    "id": ["pemanas", "AC", "boiler", "termostat", "tukang ledeng", "tukang listrik",
           "atap", "berkebun", "kebersihan", "pengecatan", "pindahan", "pengendalian hama"],
    "th": ["ระบบทำความร้อน", "แอร์", "หม้อน้ำ", "เทอร์โมสตัท", "ช่างประปา", "ช่างไฟฟ้า",
           "หลังคา", "จัดสวน", "ทำความสะอาด", "ทาสี", "ย้ายบ้าน", "กำจัดแมลง"],
    "vi": ["sưởi ấm", "điều hòa", "nồi hơi", "bộ điều nhiệt", "thợ ống nước", "thợ điện",
           "mái nhà", "làm vườn", "dọn dẹp", "sơn", "chuyển nhà", "diệt côn trùng"],
    "ms": ["pemanasan", "penghawa dingin", "dandang", "termostat", "tukang paip", "tukang elektrik",
           "bumbung", "berkebun", "pembersihan", "mengecat", "pindah rumah", "kawalan perosak"],
    "ur": ["ہیٹنگ", "اے سی", "بوائلر", "تھرموسٹیٹ", "پلمبر", "الیکٹریشن",
           "چھت کا کام", "باغبانی", "صفائی", "پینٹنگ", "شفٹنگ", "کیڑوں پر قابو"],
    "ar": ["تدفئة", "تكييف", "غلاية", "ثرموستات", "سباك", "كهربائي",
           "أسقف", "حدائق", "تنظيف", "دهان", "نقل أثاث", "مكافحة حشرات"],
    "he": ["חימום", "מיזוג אוויר", "דוד", "תרמוסטט", "שרברב", "חשמלאי",
           "גגות", "גינון", "ניקיון", "צביעה", "הובלות", "הדברת מזיקים"],
}
